#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

required_vars=(
  AZURE_SUBSCRIPTION_ID
  AZURE_RESOURCE_GROUP
  AZURE_LOCATION
  AZURE_CONTAINERAPP_ENV
  AZURE_ACR_NAME
  AZURE_CONTAINERAPP_NAME
  A2A_BACKEND_BASE_URL
  A2A_STORY_BACKEND_BASE_URL
  A2A_QUIZ_BACKEND_BASE_URL
  AZURE_OPENAI_ENDPOINT
  AZURE_OPENAI_CHAT_DEPLOYMENT_NAME
  AZURE_OPENAI_API_KEY
  EXA_API_KEY
  AZURE_SEARCH_SERVICE_ENDPOINT
  AZURE_SEARCH_INDEX_NAME
)

for var_name in "${required_vars[@]}"; do
  if [[ -z "${!var_name:-}" ]]; then
    echo "Missing required env var: ${var_name}" >&2
    exit 1
  fi
done

A2A_RPC_PATH="${A2A_RPC_PATH:-/a2a}"
A2A_STORY_RPC_PATH="${A2A_STORY_RPC_PATH:-/a2a}"
A2A_STORY_USE_PROTOCOL="${A2A_STORY_USE_PROTOCOL:-true}"
A2A_QUIZ_RPC_PATH="${A2A_QUIZ_RPC_PATH:-/a2a}"
A2A_QUIZ_USE_PROTOCOL="${A2A_QUIZ_USE_PROTOCOL:-true}"
AZURE_OPENAI_API_VERSION="${AZURE_OPENAI_API_VERSION:-preview}"
AZURE_OPENAI_EMBEDDING_ENDPOINT="${AZURE_OPENAI_EMBEDDING_ENDPOINT:-${AZURE_OPENAI_ENDPOINT:-}}"
AZURE_OPENAI_EMBEDDING_API_KEY="${AZURE_OPENAI_EMBEDDING_API_KEY:-${AZURE_OPENAI_API_KEY:-}}"
AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME="${AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME:-}"
AZURE_OPENAI_EMBEDDING_API_VERSION="${AZURE_OPENAI_EMBEDDING_API_VERSION:-2024-10-21}"
AZURE_SEARCH_USE_MANAGED_IDENTITY="${AZURE_SEARCH_USE_MANAGED_IDENTITY:-true}"
AZURE_SEARCH_MCP_ENABLED="${AZURE_SEARCH_MCP_ENABLED:-true}"
AZURE_SEARCH_FALLBACK_ENABLED="${AZURE_SEARCH_FALLBACK_ENABLED:-true}"
AZURE_SEARCH_API_VERSION="${AZURE_SEARCH_API_VERSION:-2025-09-01}"
AZURE_SEARCH_MCP_API_VERSION="${AZURE_SEARCH_MCP_API_VERSION:-2025-11-01-preview}"
AZURE_SEARCH_TOP_K="${AZURE_SEARCH_TOP_K:-6}"
AZURE_SEARCH_VECTOR_K="${AZURE_SEARCH_VECTOR_K:-20}"
AZURE_SEARCH_TIMEOUT_SECONDS="${AZURE_SEARCH_TIMEOUT_SECONDS:-30}"
AZURE_SEARCH_MCP_TIMEOUT_SECONDS="${AZURE_SEARCH_MCP_TIMEOUT_SECONDS:-30}"
AZURE_SEARCH_STUDY_ENABLED="${AZURE_SEARCH_STUDY_ENABLED:-true}"
AZURE_SEARCH_STUDY_INDEX_NAME="${AZURE_SEARCH_STUDY_INDEX_NAME:-dream-study-index}"
AZURE_SEARCH_STUDY_SESSION_FIELD="${AZURE_SEARCH_STUDY_SESSION_FIELD:-study_session_id}"
AZURE_SEARCH_STUDY_ID_FIELD="${AZURE_SEARCH_STUDY_ID_FIELD:-id}"
AZURE_SEARCH_STUDY_CONTENT_FIELD="${AZURE_SEARCH_STUDY_CONTENT_FIELD:-content}"
AZURE_SEARCH_STUDY_TITLE_FIELD="${AZURE_SEARCH_STUDY_TITLE_FIELD:-title}"
AZURE_SEARCH_STUDY_URL_FIELD="${AZURE_SEARCH_STUDY_URL_FIELD:-url}"
AZURE_SEARCH_STUDY_FILENAME_FIELD="${AZURE_SEARCH_STUDY_FILENAME_FIELD:-study_file_name}"
AZURE_SEARCH_STUDY_CHUNK_INDEX_FIELD="${AZURE_SEARCH_STUDY_CHUNK_INDEX_FIELD:-chunk_index}"
AZURE_SEARCH_STUDY_UPLOADED_AT_FIELD="${AZURE_SEARCH_STUDY_UPLOADED_AT_FIELD:-uploaded_at}"
AZURE_SEARCH_STUDY_VECTOR_FIELD="${AZURE_SEARCH_STUDY_VECTOR_FIELD:-content_vector}"
AZURE_SEARCH_STUDY_VECTOR_DIMENSIONS="${AZURE_SEARCH_STUDY_VECTOR_DIMENSIONS:-1536}"
AZURE_SEARCH_STUDY_CHUNK_SIZE_CHARS="${AZURE_SEARCH_STUDY_CHUNK_SIZE_CHARS:-1400}"
AZURE_SEARCH_STUDY_CHUNK_OVERLAP_CHARS="${AZURE_SEARCH_STUDY_CHUNK_OVERLAP_CHARS:-200}"
AZURE_SEARCH_STUDY_MAX_FILE_BYTES="${AZURE_SEARCH_STUDY_MAX_FILE_BYTES:-20000000}"
EXA_MCP_ENABLED="${EXA_MCP_ENABLED:-true}"
EXA_MCP_BASE_URL="${EXA_MCP_BASE_URL:-https://mcp.exa.ai/mcp}"
EXA_MCP_TOOLS="${EXA_MCP_TOOLS:-web_search_exa}"
EXA_MCP_REQUIRED_IN_SEARCH="${EXA_MCP_REQUIRED_IN_SEARCH:-false}"
EXA_MCP_TIMEOUT_SECONDS="${EXA_MCP_TIMEOUT_SECONDS:-20}"
EXA_SEARCH_TOP_K="${EXA_SEARCH_TOP_K:-6}"
AZURE_CONTENT_SAFETY_ENABLED="${AZURE_CONTENT_SAFETY_ENABLED:-false}"
AZURE_CONTENT_SAFETY_API_VERSION="${AZURE_CONTENT_SAFETY_API_VERSION:-2024-09-01}"
AZURE_CONTENT_SAFETY_BLOCK_SEVERITY="${AZURE_CONTENT_SAFETY_BLOCK_SEVERITY:-4}"
AZURE_CONTENT_SAFETY_TIMEOUT_SECONDS="${AZURE_CONTENT_SAFETY_TIMEOUT_SECONDS:-10}"
AZURE_CONTENT_SAFETY_FAIL_OPEN="${AZURE_CONTENT_SAFETY_FAIL_OPEN:-true}"
APPLICATIONINSIGHTS_CONNECTION_STRING="${APPLICATIONINSIGHTS_CONNECTION_STRING:-}"
AZURE_CONTAINER_CPU="${AZURE_CONTAINER_CPU:-1.0}"
AZURE_CONTAINER_MEMORY="${AZURE_CONTAINER_MEMORY:-2Gi}"
AZURE_MIN_REPLICAS="${AZURE_MIN_REPLICAS:-1}"
AZURE_MAX_REPLICAS="${AZURE_MAX_REPLICAS:-3}"
IMAGE_TAG="maf-orchestrator:$(date +%Y%m%d%H%M%S)"

if [[ "${AZURE_SEARCH_USE_MANAGED_IDENTITY}" != "true" && -z "${AZURE_SEARCH_API_KEY:-}" ]]; then
  echo "Missing required env var: AZURE_SEARCH_API_KEY (required when AZURE_SEARCH_USE_MANAGED_IDENTITY=false)" >&2
  exit 1
fi

if [[ -n "${AZURE_SEARCH_STUDY_VECTOR_FIELD}" ]]; then
  if [[ -z "${AZURE_OPENAI_EMBEDDING_ENDPOINT}" || -z "${AZURE_OPENAI_EMBEDDING_API_KEY}" || -z "${AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME}" ]]; then
    echo "AZURE_OPENAI_EMBEDDING_ENDPOINT, AZURE_OPENAI_EMBEDDING_API_KEY, and AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME are required when study vector search is enabled" >&2
    exit 1
  fi
fi

if [[ "${AZURE_CONTENT_SAFETY_ENABLED}" == "true" ]]; then
  if [[ -z "${AZURE_CONTENT_SAFETY_ENDPOINT:-}" || -z "${AZURE_CONTENT_SAFETY_API_KEY:-}" ]]; then
    echo "AZURE_CONTENT_SAFETY_ENDPOINT and AZURE_CONTENT_SAFETY_API_KEY are required when AZURE_CONTENT_SAFETY_ENABLED=true" >&2
    exit 1
  fi
fi

az account set --subscription "${AZURE_SUBSCRIPTION_ID}"

az group create \
  --name "${AZURE_RESOURCE_GROUP}" \
  --location "${AZURE_LOCATION}" \
  --output none

if ! az acr show --name "${AZURE_ACR_NAME}" --resource-group "${AZURE_RESOURCE_GROUP}" >/dev/null 2>&1; then
  az acr create \
    --name "${AZURE_ACR_NAME}" \
    --resource-group "${AZURE_RESOURCE_GROUP}" \
    --sku Basic \
    --admin-enabled true \
    --output none
fi

az acr update \
  --name "${AZURE_ACR_NAME}" \
  --resource-group "${AZURE_RESOURCE_GROUP}" \
  --admin-enabled true \
  --output none

ACR_LOGIN_SERVER="$(az acr show --name "${AZURE_ACR_NAME}" --resource-group "${AZURE_RESOURCE_GROUP}" --query loginServer -o tsv)"

echo "Building image ${IMAGE_TAG}..."
az acr build \
  --registry "${AZURE_ACR_NAME}" \
  --image "${IMAGE_TAG}" \
  "${ROOT_DIR}" \
  --output none

if ! az containerapp env show --name "${AZURE_CONTAINERAPP_ENV}" --resource-group "${AZURE_RESOURCE_GROUP}" >/dev/null 2>&1; then
  az containerapp env create \
    --name "${AZURE_CONTAINERAPP_ENV}" \
    --resource-group "${AZURE_RESOURCE_GROUP}" \
    --location "${AZURE_LOCATION}" \
    --output none
fi

ACR_USER="$(az acr credential show --name "${AZURE_ACR_NAME}" --query username -o tsv)"
ACR_PASS="$(az acr credential show --name "${AZURE_ACR_NAME}" --query passwords[0].value -o tsv)"
IMAGE_NAME="${ACR_LOGIN_SERVER}/${IMAGE_TAG}"

SECRET_ARGS=(
  "azure-openai-api-key=${AZURE_OPENAI_API_KEY}"
  "exa-api-key=${EXA_API_KEY}"
)

if [[ -n "${AZURE_SEARCH_API_KEY:-}" ]]; then
  SECRET_ARGS+=("azure-search-api-key=${AZURE_SEARCH_API_KEY}")
fi

if [[ -n "${AZURE_OPENAI_EMBEDDING_API_KEY:-}" ]]; then
  SECRET_ARGS+=("azure-openai-embedding-api-key=${AZURE_OPENAI_EMBEDDING_API_KEY}")
fi

if [[ -n "${APPLICATIONINSIGHTS_CONNECTION_STRING}" ]]; then
  SECRET_ARGS+=("appinsights-connection-string=${APPLICATIONINSIGHTS_CONNECTION_STRING}")
fi

if [[ "${AZURE_CONTENT_SAFETY_ENABLED}" == "true" ]]; then
  SECRET_ARGS+=("azure-content-safety-api-key=${AZURE_CONTENT_SAFETY_API_KEY}")
fi

ENV_ARGS=(
  "AGENT_PROVIDER=azure"
  "AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}"
  "AZURE_OPENAI_CHAT_DEPLOYMENT_NAME=${AZURE_OPENAI_CHAT_DEPLOYMENT_NAME}"
  "AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}"
  "AZURE_OPENAI_API_KEY=secretref:azure-openai-api-key"
  "EXA_API_KEY=secretref:exa-api-key"
  "EXA_MCP_ENABLED=${EXA_MCP_ENABLED}"
  "EXA_MCP_BASE_URL=${EXA_MCP_BASE_URL}"
  "EXA_MCP_TOOLS=${EXA_MCP_TOOLS}"
  "EXA_MCP_REQUIRED_IN_SEARCH=${EXA_MCP_REQUIRED_IN_SEARCH}"
  "EXA_MCP_TIMEOUT_SECONDS=${EXA_MCP_TIMEOUT_SECONDS}"
  "EXA_SEARCH_TOP_K=${EXA_SEARCH_TOP_K}"
  "A2A_BACKEND_BASE_URL=${A2A_BACKEND_BASE_URL}"
  "A2A_RPC_PATH=${A2A_RPC_PATH}"
  "A2A_USE_PROTOCOL=true"
  "A2A_STORY_BACKEND_BASE_URL=${A2A_STORY_BACKEND_BASE_URL}"
  "A2A_STORY_RPC_PATH=${A2A_STORY_RPC_PATH}"
  "A2A_STORY_USE_PROTOCOL=${A2A_STORY_USE_PROTOCOL}"
  "A2A_QUIZ_BACKEND_BASE_URL=${A2A_QUIZ_BACKEND_BASE_URL}"
  "A2A_QUIZ_RPC_PATH=${A2A_QUIZ_RPC_PATH}"
  "A2A_QUIZ_USE_PROTOCOL=${A2A_QUIZ_USE_PROTOCOL}"
  "DREAM_DATA_DIR=/app/data"
  "AZURE_SEARCH_SERVICE_ENDPOINT=${AZURE_SEARCH_SERVICE_ENDPOINT}"
  "AZURE_SEARCH_USE_MANAGED_IDENTITY=${AZURE_SEARCH_USE_MANAGED_IDENTITY}"
  "AZURE_SEARCH_INDEX_NAME=${AZURE_SEARCH_INDEX_NAME}"
  "AZURE_SEARCH_MCP_ENABLED=${AZURE_SEARCH_MCP_ENABLED}"
  "AZURE_SEARCH_FALLBACK_ENABLED=${AZURE_SEARCH_FALLBACK_ENABLED}"
  "AZURE_SEARCH_API_VERSION=${AZURE_SEARCH_API_VERSION}"
  "AZURE_SEARCH_MCP_API_VERSION=${AZURE_SEARCH_MCP_API_VERSION}"
  "AZURE_SEARCH_TOP_K=${AZURE_SEARCH_TOP_K}"
  "AZURE_SEARCH_VECTOR_K=${AZURE_SEARCH_VECTOR_K}"
  "AZURE_SEARCH_TIMEOUT_SECONDS=${AZURE_SEARCH_TIMEOUT_SECONDS}"
  "AZURE_SEARCH_MCP_TIMEOUT_SECONDS=${AZURE_SEARCH_MCP_TIMEOUT_SECONDS}"
  "AZURE_SEARCH_STUDY_ENABLED=${AZURE_SEARCH_STUDY_ENABLED}"
  "AZURE_SEARCH_STUDY_INDEX_NAME=${AZURE_SEARCH_STUDY_INDEX_NAME}"
  "AZURE_SEARCH_STUDY_SESSION_FIELD=${AZURE_SEARCH_STUDY_SESSION_FIELD}"
  "AZURE_SEARCH_STUDY_ID_FIELD=${AZURE_SEARCH_STUDY_ID_FIELD}"
  "AZURE_SEARCH_STUDY_CONTENT_FIELD=${AZURE_SEARCH_STUDY_CONTENT_FIELD}"
  "AZURE_SEARCH_STUDY_TITLE_FIELD=${AZURE_SEARCH_STUDY_TITLE_FIELD}"
  "AZURE_SEARCH_STUDY_URL_FIELD=${AZURE_SEARCH_STUDY_URL_FIELD}"
  "AZURE_SEARCH_STUDY_FILENAME_FIELD=${AZURE_SEARCH_STUDY_FILENAME_FIELD}"
  "AZURE_SEARCH_STUDY_CHUNK_INDEX_FIELD=${AZURE_SEARCH_STUDY_CHUNK_INDEX_FIELD}"
  "AZURE_SEARCH_STUDY_UPLOADED_AT_FIELD=${AZURE_SEARCH_STUDY_UPLOADED_AT_FIELD}"
  "AZURE_SEARCH_STUDY_VECTOR_FIELD=${AZURE_SEARCH_STUDY_VECTOR_FIELD}"
  "AZURE_SEARCH_STUDY_VECTOR_DIMENSIONS=${AZURE_SEARCH_STUDY_VECTOR_DIMENSIONS}"
  "AZURE_SEARCH_STUDY_CHUNK_SIZE_CHARS=${AZURE_SEARCH_STUDY_CHUNK_SIZE_CHARS}"
  "AZURE_SEARCH_STUDY_CHUNK_OVERLAP_CHARS=${AZURE_SEARCH_STUDY_CHUNK_OVERLAP_CHARS}"
  "AZURE_SEARCH_STUDY_MAX_FILE_BYTES=${AZURE_SEARCH_STUDY_MAX_FILE_BYTES}"
  "AZURE_OPENAI_EMBEDDING_ENDPOINT=${AZURE_OPENAI_EMBEDDING_ENDPOINT}"
  "AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME=${AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME}"
  "AZURE_OPENAI_EMBEDDING_API_VERSION=${AZURE_OPENAI_EMBEDDING_API_VERSION}"
  "AZURE_OPENAI_EMBEDDING_API_KEY=secretref:azure-openai-embedding-api-key"
  "AZURE_CONTENT_SAFETY_ENABLED=${AZURE_CONTENT_SAFETY_ENABLED}"
  "AZURE_CONTENT_SAFETY_API_VERSION=${AZURE_CONTENT_SAFETY_API_VERSION}"
  "AZURE_CONTENT_SAFETY_BLOCK_SEVERITY=${AZURE_CONTENT_SAFETY_BLOCK_SEVERITY}"
  "AZURE_CONTENT_SAFETY_TIMEOUT_SECONDS=${AZURE_CONTENT_SAFETY_TIMEOUT_SECONDS}"
  "AZURE_CONTENT_SAFETY_FAIL_OPEN=${AZURE_CONTENT_SAFETY_FAIL_OPEN}"
)

if [[ "${AZURE_SEARCH_USE_MANAGED_IDENTITY}" != "true" ]]; then
  ENV_ARGS+=("AZURE_SEARCH_API_KEY=secretref:azure-search-api-key")
fi

if [[ -n "${AZURE_SEARCH_SEMANTIC_CONFIGURATION:-}" ]]; then
  ENV_ARGS+=("AZURE_SEARCH_SEMANTIC_CONFIGURATION=${AZURE_SEARCH_SEMANTIC_CONFIGURATION}")
fi
if [[ -n "${AZURE_SEARCH_SELECT_FIELDS_RAW:-}" ]]; then
  ENV_ARGS+=("AZURE_SEARCH_SELECT_FIELDS_RAW=${AZURE_SEARCH_SELECT_FIELDS_RAW}")
fi
if [[ -n "${AZURE_SEARCH_CONTENT_FIELDS_RAW:-}" ]]; then
  ENV_ARGS+=("AZURE_SEARCH_CONTENT_FIELDS_RAW=${AZURE_SEARCH_CONTENT_FIELDS_RAW}")
fi
if [[ -n "${AZURE_SEARCH_TITLE_FIELDS_RAW:-}" ]]; then
  ENV_ARGS+=("AZURE_SEARCH_TITLE_FIELDS_RAW=${AZURE_SEARCH_TITLE_FIELDS_RAW}")
fi
if [[ -n "${AZURE_SEARCH_URL_FIELDS_RAW:-}" ]]; then
  ENV_ARGS+=("AZURE_SEARCH_URL_FIELDS_RAW=${AZURE_SEARCH_URL_FIELDS_RAW}")
fi
if [[ -n "${AZURE_SEARCH_VECTOR_FIELDS_RAW:-}" ]]; then
  ENV_ARGS+=("AZURE_SEARCH_VECTOR_FIELDS_RAW=${AZURE_SEARCH_VECTOR_FIELDS_RAW}")
fi

if [[ "${AZURE_CONTENT_SAFETY_ENABLED}" == "true" ]]; then
  ENV_ARGS+=("AZURE_CONTENT_SAFETY_ENDPOINT=${AZURE_CONTENT_SAFETY_ENDPOINT}")
  ENV_ARGS+=("AZURE_CONTENT_SAFETY_API_KEY=secretref:azure-content-safety-api-key")
fi

if [[ -n "${APPLICATIONINSIGHTS_CONNECTION_STRING}" ]]; then
  ENV_ARGS+=("APPLICATIONINSIGHTS_CONNECTION_STRING=secretref:appinsights-connection-string")
fi

if az containerapp show --name "${AZURE_CONTAINERAPP_NAME}" --resource-group "${AZURE_RESOURCE_GROUP}" >/dev/null 2>&1; then
  az containerapp secret set \
    --name "${AZURE_CONTAINERAPP_NAME}" \
    --resource-group "${AZURE_RESOURCE_GROUP}" \
    --secrets "${SECRET_ARGS[@]}" \
    --output none

  az containerapp update \
    --name "${AZURE_CONTAINERAPP_NAME}" \
    --resource-group "${AZURE_RESOURCE_GROUP}" \
    --image "${IMAGE_NAME}" \
    --cpu "${AZURE_CONTAINER_CPU}" \
    --memory "${AZURE_CONTAINER_MEMORY}" \
    --min-replicas "${AZURE_MIN_REPLICAS}" \
    --max-replicas "${AZURE_MAX_REPLICAS}" \
    --set-env-vars "${ENV_ARGS[@]}" \
    --output none
else
  az containerapp create \
    --name "${AZURE_CONTAINERAPP_NAME}" \
    --resource-group "${AZURE_RESOURCE_GROUP}" \
    --environment "${AZURE_CONTAINERAPP_ENV}" \
    --image "${IMAGE_NAME}" \
    --target-port 8080 \
    --ingress external \
    --registry-server "${ACR_LOGIN_SERVER}" \
    --registry-username "${ACR_USER}" \
    --registry-password "${ACR_PASS}" \
    --cpu "${AZURE_CONTAINER_CPU}" \
    --memory "${AZURE_CONTAINER_MEMORY}" \
    --min-replicas "${AZURE_MIN_REPLICAS}" \
    --max-replicas "${AZURE_MAX_REPLICAS}" \
    --secrets "${SECRET_ARGS[@]}" \
    --env-vars "${ENV_ARGS[@]}" \
    --output none
fi

if [[ "${AZURE_SEARCH_USE_MANAGED_IDENTITY}" == "true" ]]; then
  az containerapp identity assign \
    --name "${AZURE_CONTAINERAPP_NAME}" \
    --resource-group "${AZURE_RESOURCE_GROUP}" \
    --system-assigned \
    --output none
fi

FQDN="$(az containerapp show --name "${AZURE_CONTAINERAPP_NAME}" --resource-group "${AZURE_RESOURCE_GROUP}" --query properties.configuration.ingress.fqdn -o tsv)"

echo "Deployment complete"
echo "App URL: https://${FQDN}"
echo "Health URL: https://${FQDN}/health"
